/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ContactGroupEntry service. Represents a row in the &quot;TBL_CONTACT_GROUP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.ContactGroupEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.ContactGroupEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ContactGroupEntry
 * @see vn.com.fis.portal.model.impl.ContactGroupEntryImpl
 * @see vn.com.fis.portal.model.impl.ContactGroupEntryModelImpl
 * @generated
 */
public interface ContactGroupEntryModel extends BaseModel<ContactGroupEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact group entry model instance should use the {@link ContactGroupEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this contact group entry.
	 *
	 * @return the primary key of this contact group entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact group entry.
	 *
	 * @param primaryKey the primary key of this contact group entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact group ID of this contact group entry.
	 *
	 * @return the contact group ID of this contact group entry
	 */
	public long getContactGroupId();

	/**
	 * Sets the contact group ID of this contact group entry.
	 *
	 * @param contactGroupId the contact group ID of this contact group entry
	 */
	public void setContactGroupId(long contactGroupId);

	/**
	 * Returns the contact group name of this contact group entry.
	 *
	 * @return the contact group name of this contact group entry
	 */
	@AutoEscape
	public String getContactGroupName();

	/**
	 * Sets the contact group name of this contact group entry.
	 *
	 * @param contactGroupName the contact group name of this contact group entry
	 */
	public void setContactGroupName(String contactGroupName);

	/**
	 * Returns the description of this contact group entry.
	 *
	 * @return the description of this contact group entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this contact group entry.
	 *
	 * @param description the description of this contact group entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the contact group type of this contact group entry.
	 *
	 * @return the contact group type of this contact group entry
	 */
	public int getContactGroupType();

	/**
	 * Sets the contact group type of this contact group entry.
	 *
	 * @param contactGroupType the contact group type of this contact group entry
	 */
	public void setContactGroupType(int contactGroupType);

	/**
	 * Returns the user ID of this contact group entry.
	 *
	 * @return the user ID of this contact group entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this contact group entry.
	 *
	 * @param userId the user ID of this contact group entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact group entry.
	 *
	 * @return the user uuid of this contact group entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this contact group entry.
	 *
	 * @param userUuid the user uuid of this contact group entry
	 */
	public void setUserUuid(String userUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ContactGroupEntry contactGroupEntry);

	public int hashCode();

	public CacheModel<ContactGroupEntry> toCacheModel();

	public ContactGroupEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}