/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RatingEntry service. Represents a row in the &quot;TBL_RATING&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.RatingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.RatingEntryImpl}.
 * </p>
 *
 * @author loind
 * @see RatingEntry
 * @see vn.com.fis.portal.model.impl.RatingEntryImpl
 * @see vn.com.fis.portal.model.impl.RatingEntryModelImpl
 * @generated
 */
public interface RatingEntryModel extends BaseModel<RatingEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rating entry model instance should use the {@link RatingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this rating entry.
	 *
	 * @return the primary key of this rating entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rating entry.
	 *
	 * @param primaryKey the primary key of this rating entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rating ID of this rating entry.
	 *
	 * @return the rating ID of this rating entry
	 */
	public long getRatingId();

	/**
	 * Sets the rating ID of this rating entry.
	 *
	 * @param ratingId the rating ID of this rating entry
	 */
	public void setRatingId(long ratingId);

	/**
	 * Returns the video ID of this rating entry.
	 *
	 * @return the video ID of this rating entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this rating entry.
	 *
	 * @param videoId the video ID of this rating entry
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the user ID of this rating entry.
	 *
	 * @return the user ID of this rating entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rating entry.
	 *
	 * @param userId the user ID of this rating entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rating entry.
	 *
	 * @return the user uuid of this rating entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rating entry.
	 *
	 * @param userUuid the user uuid of this rating entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the code of this rating entry.
	 *
	 * @return the code of this rating entry
	 */
	public int getCode();

	/**
	 * Sets the code of this rating entry.
	 *
	 * @param code the code of this rating entry
	 */
	public void setCode(int code);

	/**
	 * Returns the date_ of this rating entry.
	 *
	 * @return the date_ of this rating entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this rating entry.
	 *
	 * @param date_ the date_ of this rating entry
	 */
	public void setDate_(Date date_);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(RatingEntry ratingEntry);

	public int hashCode();

	public CacheModel<RatingEntry> toCacheModel();

	public RatingEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}