/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoEntry service. Represents a row in the &quot;TBL_VIDEO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.VideoEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.VideoEntryImpl}.
 * </p>
 *
 * @author loind
 * @see VideoEntry
 * @see vn.com.fis.portal.model.impl.VideoEntryImpl
 * @see vn.com.fis.portal.model.impl.VideoEntryModelImpl
 * @generated
 */
public interface VideoEntryModel extends BaseModel<VideoEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video entry model instance should use the {@link VideoEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this video entry.
	 *
	 * @return the primary key of this video entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video entry.
	 *
	 * @param primaryKey the primary key of this video entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video ID of this video entry.
	 *
	 * @return the video ID of this video entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video entry.
	 *
	 * @param videoId the video ID of this video entry
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the video name of this video entry.
	 *
	 * @return the video name of this video entry
	 */
	@AutoEscape
	public String getVideoName();

	/**
	 * Sets the video name of this video entry.
	 *
	 * @param videoName the video name of this video entry
	 */
	public void setVideoName(String videoName);

	/**
	 * Returns the description of this video entry.
	 *
	 * @return the description of this video entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this video entry.
	 *
	 * @param description the description of this video entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the view count of this video entry.
	 *
	 * @return the view count of this video entry
	 */
	public long getViewCount();

	/**
	 * Sets the view count of this video entry.
	 *
	 * @param viewCount the view count of this video entry
	 */
	public void setViewCount(long viewCount);

	/**
	 * Returns the date_ of this video entry.
	 *
	 * @return the date_ of this video entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this video entry.
	 *
	 * @param date_ the date_ of this video entry
	 */
	public void setDate_(Date date_);

	/**
	 * Returns the small image url of this video entry.
	 *
	 * @return the small image url of this video entry
	 */
	@AutoEscape
	public String getSmallImageUrl();

	/**
	 * Sets the small image url of this video entry.
	 *
	 * @param smallImageUrl the small image url of this video entry
	 */
	public void setSmallImageUrl(String smallImageUrl);

	/**
	 * Returns the large image url of this video entry.
	 *
	 * @return the large image url of this video entry
	 */
	@AutoEscape
	public String getLargeImageUrl();

	/**
	 * Sets the large image url of this video entry.
	 *
	 * @param largeImageUrl the large image url of this video entry
	 */
	public void setLargeImageUrl(String largeImageUrl);

	/**
	 * Returns the access modifier of this video entry.
	 *
	 * @return the access modifier of this video entry
	 */
	public int getAccessModifier();

	/**
	 * Sets the access modifier of this video entry.
	 *
	 * @param accessModifier the access modifier of this video entry
	 */
	public void setAccessModifier(int accessModifier);

	/**
	 * Returns the uploader ID of this video entry.
	 *
	 * @return the uploader ID of this video entry
	 */
	public long getUploaderId();

	/**
	 * Sets the uploader ID of this video entry.
	 *
	 * @param uploaderId the uploader ID of this video entry
	 */
	public void setUploaderId(long uploaderId);

	/**
	 * Returns the folder ID of this video entry.
	 *
	 * @return the folder ID of this video entry
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this video entry.
	 *
	 * @param folderId the folder ID of this video entry
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the status of this video entry.
	 *
	 * @return the status of this video entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this video entry.
	 *
	 * @param status the status of this video entry
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VideoEntry videoEntry);

	public int hashCode();

	public CacheModel<VideoEntry> toCacheModel();

	public VideoEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}