/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoUserEntry service. Represents a row in the &quot;TBL_VIDEO_USER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.VideoUserEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.VideoUserEntryImpl}.
 * </p>
 *
 * @author loind
 * @see VideoUserEntry
 * @see vn.com.fis.portal.model.impl.VideoUserEntryImpl
 * @see vn.com.fis.portal.model.impl.VideoUserEntryModelImpl
 * @generated
 */
public interface VideoUserEntryModel extends BaseModel<VideoUserEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video user entry model instance should use the {@link VideoUserEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this video user entry.
	 *
	 * @return the primary key of this video user entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video user entry.
	 *
	 * @param primaryKey the primary key of this video user entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video user ID of this video user entry.
	 *
	 * @return the video user ID of this video user entry
	 */
	public long getVideoUserId();

	/**
	 * Sets the video user ID of this video user entry.
	 *
	 * @param videoUserId the video user ID of this video user entry
	 */
	public void setVideoUserId(long videoUserId);

	/**
	 * Returns the video user uuid of this video user entry.
	 *
	 * @return the video user uuid of this video user entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getVideoUserUuid() throws SystemException;

	/**
	 * Sets the video user uuid of this video user entry.
	 *
	 * @param videoUserUuid the video user uuid of this video user entry
	 */
	public void setVideoUserUuid(String videoUserUuid);

	/**
	 * Returns the video ID of this video user entry.
	 *
	 * @return the video ID of this video user entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video user entry.
	 *
	 * @param videoId the video ID of this video user entry
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the user ID of this video user entry.
	 *
	 * @return the user ID of this video user entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this video user entry.
	 *
	 * @param userId the user ID of this video user entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this video user entry.
	 *
	 * @return the user uuid of this video user entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this video user entry.
	 *
	 * @param userUuid the user uuid of this video user entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the origin code of this video user entry.
	 *
	 * @return the origin code of this video user entry
	 */
	public int getOriginCode();

	/**
	 * Sets the origin code of this video user entry.
	 *
	 * @param originCode the origin code of this video user entry
	 */
	public void setOriginCode(int originCode);

	/**
	 * Returns the date_ of this video user entry.
	 *
	 * @return the date_ of this video user entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this video user entry.
	 *
	 * @param date_ the date_ of this video user entry
	 */
	public void setDate_(Date date_);

	/**
	 * Returns the start date of this video user entry.
	 *
	 * @return the start date of this video user entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this video user entry.
	 *
	 * @param startDate the start date of this video user entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this video user entry.
	 *
	 * @return the end date of this video user entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this video user entry.
	 *
	 * @param endDate the end date of this video user entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the sender ID of this video user entry.
	 *
	 * @return the sender ID of this video user entry
	 */
	public long getSenderId();

	/**
	 * Sets the sender ID of this video user entry.
	 *
	 * @param senderId the sender ID of this video user entry
	 */
	public void setSenderId(long senderId);

	/**
	 * Returns the status of this video user entry.
	 *
	 * @return the status of this video user entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this video user entry.
	 *
	 * @param status the status of this video user entry
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VideoUserEntry videoUserEntry);

	public int hashCode();

	public CacheModel<VideoUserEntry> toCacheModel();

	public VideoUserEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}