/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ViolationVideoEntry service. Represents a row in the &quot;TBL_VIOLATION_VIDEO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.ViolationVideoEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.ViolationVideoEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ViolationVideoEntry
 * @see vn.com.fis.portal.model.impl.ViolationVideoEntryImpl
 * @see vn.com.fis.portal.model.impl.ViolationVideoEntryModelImpl
 * @generated
 */
public interface ViolationVideoEntryModel extends BaseModel<ViolationVideoEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a violation video entry model instance should use the {@link ViolationVideoEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this violation video entry.
	 *
	 * @return the primary key of this violation video entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this violation video entry.
	 *
	 * @param primaryKey the primary key of this violation video entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the violation video ID of this violation video entry.
	 *
	 * @return the violation video ID of this violation video entry
	 */
	public long getViolationVideoId();

	/**
	 * Sets the violation video ID of this violation video entry.
	 *
	 * @param violationVideoId the violation video ID of this violation video entry
	 */
	public void setViolationVideoId(long violationVideoId);

	/**
	 * Returns the violation ID of this violation video entry.
	 *
	 * @return the violation ID of this violation video entry
	 */
	public long getViolationId();

	/**
	 * Sets the violation ID of this violation video entry.
	 *
	 * @param violationId the violation ID of this violation video entry
	 */
	public void setViolationId(long violationId);

	/**
	 * Returns the video ID of this violation video entry.
	 *
	 * @return the video ID of this violation video entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this violation video entry.
	 *
	 * @param videoId the video ID of this violation video entry
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the user ID of this violation video entry.
	 *
	 * @return the user ID of this violation video entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this violation video entry.
	 *
	 * @param userId the user ID of this violation video entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this violation video entry.
	 *
	 * @return the user uuid of this violation video entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this violation video entry.
	 *
	 * @param userUuid the user uuid of this violation video entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the date_ of this violation video entry.
	 *
	 * @return the date_ of this violation video entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this violation video entry.
	 *
	 * @param date_ the date_ of this violation video entry
	 */
	public void setDate_(Date date_);

	/**
	 * Returns the description of this violation video entry.
	 *
	 * @return the description of this violation video entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this violation video entry.
	 *
	 * @param description the description of this violation video entry
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ViolationVideoEntry violationVideoEntry);

	public int hashCode();

	public CacheModel<ViolationVideoEntry> toCacheModel();

	public ViolationVideoEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}