/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServicePackageEntry service. Represents a row in the &quot;TBL_SERVICE_PACKAGE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.ServicePackageEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.ServicePackageEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ServicePackageEntry
 * @see vn.com.fis.portal.model.impl.ServicePackageEntryImpl
 * @see vn.com.fis.portal.model.impl.ServicePackageEntryModelImpl
 * @generated
 */
public interface ServicePackageEntryModel extends BaseModel<ServicePackageEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service package entry model instance should use the {@link ServicePackageEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this service package entry.
	 *
	 * @return the primary key of this service package entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service package entry.
	 *
	 * @param primaryKey the primary key of this service package entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the service package ID of this service package entry.
	 *
	 * @return the service package ID of this service package entry
	 */
	public long getServicePackageId();

	/**
	 * Sets the service package ID of this service package entry.
	 *
	 * @param servicePackageId the service package ID of this service package entry
	 */
	public void setServicePackageId(long servicePackageId);

	/**
	 * Returns the service package name of this service package entry.
	 *
	 * @return the service package name of this service package entry
	 */
	@AutoEscape
	public String getServicePackageName();

	/**
	 * Sets the service package name of this service package entry.
	 *
	 * @param servicePackageName the service package name of this service package entry
	 */
	public void setServicePackageName(String servicePackageName);

	/**
	 * Returns the service package code of this service package entry.
	 *
	 * @return the service package code of this service package entry
	 */
	@AutoEscape
	public String getServicePackageCode();

	/**
	 * Sets the service package code of this service package entry.
	 *
	 * @param servicePackageCode the service package code of this service package entry
	 */
	public void setServicePackageCode(String servicePackageCode);

	/**
	 * Returns the description of this service package entry.
	 *
	 * @return the description of this service package entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this service package entry.
	 *
	 * @param description the description of this service package entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the total file of this service package entry.
	 *
	 * @return the total file of this service package entry
	 */
	public int getTotalFile();

	/**
	 * Sets the total file of this service package entry.
	 *
	 * @param totalFile the total file of this service package entry
	 */
	public void setTotalFile(int totalFile);

	/**
	 * Returns the create date of this service package entry.
	 *
	 * @return the create date of this service package entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this service package entry.
	 *
	 * @param createDate the create date of this service package entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service package entry.
	 *
	 * @return the modified date of this service package entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service package entry.
	 *
	 * @param modifiedDate the modified date of this service package entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service ID of this service package entry.
	 *
	 * @return the service ID of this service package entry
	 */
	public long getServiceId();

	/**
	 * Sets the service ID of this service package entry.
	 *
	 * @param serviceId the service ID of this service package entry
	 */
	public void setServiceId(long serviceId);

	/**
	 * Returns the status of this service package entry.
	 *
	 * @return the status of this service package entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this service package entry.
	 *
	 * @param status the status of this service package entry
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ServicePackageEntry servicePackageEntry);

	public int hashCode();

	public CacheModel<ServicePackageEntry> toCacheModel();

	public ServicePackageEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}