/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.fis.portal.model.ContactGroupVideoGroupEntry;
import vn.com.fis.portal.model.ContactGroupVideoGroupEntryModel;
import vn.com.fis.portal.model.ContactGroupVideoGroupEntrySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the ContactGroupVideoGroupEntry service. Represents a row in the &quot;TBL_CONTACT_GROUP_VIDEO_GROUP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.fis.portal.model.ContactGroupVideoGroupEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactGroupVideoGroupEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ContactGroupVideoGroupEntryImpl
 * @see vn.com.fis.portal.model.ContactGroupVideoGroupEntry
 * @see vn.com.fis.portal.model.ContactGroupVideoGroupEntryModel
 * @generated
 */
@JSON(strict = true)
public class ContactGroupVideoGroupEntryModelImpl extends BaseModelImpl<ContactGroupVideoGroupEntry>
	implements ContactGroupVideoGroupEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact group video group entry model instance should use the {@link vn.com.fis.portal.model.ContactGroupVideoGroupEntry} interface instead.
	 */
	public static final String TABLE_NAME = "TBL_CONTACT_GROUP_VIDEO_GROUP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "contactGroupVideoGroupEntryId", Types.BIGINT },
			{ "contactGroupId", Types.BIGINT },
			{ "videoGroupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table TBL_CONTACT_GROUP_VIDEO_GROUP (contactGroupVideoGroupEntryId LONG not null primary key,contactGroupId LONG,videoGroupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table TBL_CONTACT_GROUP_VIDEO_GROUP";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.fis.portal.model.ContactGroupVideoGroupEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.fis.portal.model.ContactGroupVideoGroupEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.fis.portal.model.ContactGroupVideoGroupEntry"),
			true);
	public static long CONTACTGROUPID_COLUMN_BITMASK = 1L;
	public static long VIDEOGROUPID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContactGroupVideoGroupEntry toModel(
		ContactGroupVideoGroupEntrySoap soapModel) {
		ContactGroupVideoGroupEntry model = new ContactGroupVideoGroupEntryImpl();

		model.setContactGroupVideoGroupEntryId(soapModel.getContactGroupVideoGroupEntryId());
		model.setContactGroupId(soapModel.getContactGroupId());
		model.setVideoGroupId(soapModel.getVideoGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContactGroupVideoGroupEntry> toModels(
		ContactGroupVideoGroupEntrySoap[] soapModels) {
		List<ContactGroupVideoGroupEntry> models = new ArrayList<ContactGroupVideoGroupEntry>(soapModels.length);

		for (ContactGroupVideoGroupEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.fis.portal.model.ContactGroupVideoGroupEntry"));

	public ContactGroupVideoGroupEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _contactGroupVideoGroupEntryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setContactGroupVideoGroupEntryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_contactGroupVideoGroupEntryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ContactGroupVideoGroupEntry.class;
	}

	public String getModelClassName() {
		return ContactGroupVideoGroupEntry.class.getName();
	}

	@JSON
	public long getContactGroupVideoGroupEntryId() {
		return _contactGroupVideoGroupEntryId;
	}

	public void setContactGroupVideoGroupEntryId(
		long contactGroupVideoGroupEntryId) {
		_contactGroupVideoGroupEntryId = contactGroupVideoGroupEntryId;
	}

	@JSON
	public long getContactGroupId() {
		return _contactGroupId;
	}

	public void setContactGroupId(long contactGroupId) {
		_columnBitmask |= CONTACTGROUPID_COLUMN_BITMASK;

		if (!_setOriginalContactGroupId) {
			_setOriginalContactGroupId = true;

			_originalContactGroupId = _contactGroupId;
		}

		_contactGroupId = contactGroupId;
	}

	public long getOriginalContactGroupId() {
		return _originalContactGroupId;
	}

	@JSON
	public long getVideoGroupId() {
		return _videoGroupId;
	}

	public void setVideoGroupId(long videoGroupId) {
		_columnBitmask |= VIDEOGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVideoGroupId) {
			_setOriginalVideoGroupId = true;

			_originalVideoGroupId = _videoGroupId;
		}

		_videoGroupId = videoGroupId;
	}

	public long getOriginalVideoGroupId() {
		return _originalVideoGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ContactGroupVideoGroupEntry toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ContactGroupVideoGroupEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					ContactGroupVideoGroupEntry.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ContactGroupVideoGroupEntryImpl contactGroupVideoGroupEntryImpl = new ContactGroupVideoGroupEntryImpl();

		contactGroupVideoGroupEntryImpl.setContactGroupVideoGroupEntryId(getContactGroupVideoGroupEntryId());
		contactGroupVideoGroupEntryImpl.setContactGroupId(getContactGroupId());
		contactGroupVideoGroupEntryImpl.setVideoGroupId(getVideoGroupId());

		contactGroupVideoGroupEntryImpl.resetOriginalValues();

		return contactGroupVideoGroupEntryImpl;
	}

	public int compareTo(
		ContactGroupVideoGroupEntry contactGroupVideoGroupEntry) {
		long primaryKey = contactGroupVideoGroupEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ContactGroupVideoGroupEntry contactGroupVideoGroupEntry = null;

		try {
			contactGroupVideoGroupEntry = (ContactGroupVideoGroupEntry)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = contactGroupVideoGroupEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ContactGroupVideoGroupEntryModelImpl contactGroupVideoGroupEntryModelImpl =
			this;

		contactGroupVideoGroupEntryModelImpl._originalContactGroupId = contactGroupVideoGroupEntryModelImpl._contactGroupId;

		contactGroupVideoGroupEntryModelImpl._setOriginalContactGroupId = false;

		contactGroupVideoGroupEntryModelImpl._originalVideoGroupId = contactGroupVideoGroupEntryModelImpl._videoGroupId;

		contactGroupVideoGroupEntryModelImpl._setOriginalVideoGroupId = false;

		contactGroupVideoGroupEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactGroupVideoGroupEntry> toCacheModel() {
		ContactGroupVideoGroupEntryCacheModel contactGroupVideoGroupEntryCacheModel =
			new ContactGroupVideoGroupEntryCacheModel();

		contactGroupVideoGroupEntryCacheModel.contactGroupVideoGroupEntryId = getContactGroupVideoGroupEntryId();

		contactGroupVideoGroupEntryCacheModel.contactGroupId = getContactGroupId();

		contactGroupVideoGroupEntryCacheModel.videoGroupId = getVideoGroupId();

		return contactGroupVideoGroupEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{contactGroupVideoGroupEntryId=");
		sb.append(getContactGroupVideoGroupEntryId());
		sb.append(", contactGroupId=");
		sb.append(getContactGroupId());
		sb.append(", videoGroupId=");
		sb.append(getVideoGroupId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("vn.com.fis.portal.model.ContactGroupVideoGroupEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>contactGroupVideoGroupEntryId</column-name><column-value><![CDATA[");
		sb.append(getContactGroupVideoGroupEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactGroupId</column-name><column-value><![CDATA[");
		sb.append(getContactGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoGroupId</column-name><column-value><![CDATA[");
		sb.append(getVideoGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ContactGroupVideoGroupEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ContactGroupVideoGroupEntry.class
		};
	private long _contactGroupVideoGroupEntryId;
	private long _contactGroupId;
	private long _originalContactGroupId;
	private boolean _setOriginalContactGroupId;
	private long _videoGroupId;
	private long _originalVideoGroupId;
	private boolean _setOriginalVideoGroupId;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private ContactGroupVideoGroupEntry _escapedModelProxy;
}