/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.fis.portal.model.ViolationVideoEntry;
import vn.com.fis.portal.model.ViolationVideoEntryModel;
import vn.com.fis.portal.model.ViolationVideoEntrySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the ViolationVideoEntry service. Represents a row in the &quot;TBL_VIOLATION_VIDEO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.fis.portal.model.ViolationVideoEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViolationVideoEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ViolationVideoEntryImpl
 * @see vn.com.fis.portal.model.ViolationVideoEntry
 * @see vn.com.fis.portal.model.ViolationVideoEntryModel
 * @generated
 */
@JSON(strict = true)
public class ViolationVideoEntryModelImpl extends BaseModelImpl<ViolationVideoEntry>
	implements ViolationVideoEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a violation video entry model instance should use the {@link vn.com.fis.portal.model.ViolationVideoEntry} interface instead.
	 */
	public static final String TABLE_NAME = "TBL_VIOLATION_VIDEO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "violationVideoId", Types.BIGINT },
			{ "violationId", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "date_", Types.TIMESTAMP },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TBL_VIOLATION_VIDEO (violationVideoId LONG not null primary key,violationId LONG,videoId LONG,userId LONG,date_ DATE null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TBL_VIOLATION_VIDEO";
	public static final String ORDER_BY_JPQL = " ORDER BY violationVideoEntry.date_ ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TBL_VIOLATION_VIDEO.date_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.fis.portal.model.ViolationVideoEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.fis.portal.model.ViolationVideoEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.fis.portal.model.ViolationVideoEntry"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long VIDEOID_COLUMN_BITMASK = 2L;
	public static long VIOLATIONID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ViolationVideoEntry toModel(ViolationVideoEntrySoap soapModel) {
		ViolationVideoEntry model = new ViolationVideoEntryImpl();

		model.setViolationVideoId(soapModel.getViolationVideoId());
		model.setViolationId(soapModel.getViolationId());
		model.setVideoId(soapModel.getVideoId());
		model.setUserId(soapModel.getUserId());
		model.setDate_(soapModel.getDate_());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ViolationVideoEntry> toModels(
		ViolationVideoEntrySoap[] soapModels) {
		List<ViolationVideoEntry> models = new ArrayList<ViolationVideoEntry>(soapModels.length);

		for (ViolationVideoEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.fis.portal.model.ViolationVideoEntry"));

	public ViolationVideoEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _violationVideoId;
	}

	public void setPrimaryKey(long primaryKey) {
		setViolationVideoId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_violationVideoId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ViolationVideoEntry.class;
	}

	public String getModelClassName() {
		return ViolationVideoEntry.class.getName();
	}

	@JSON
	public long getViolationVideoId() {
		return _violationVideoId;
	}

	public void setViolationVideoId(long violationVideoId) {
		_violationVideoId = violationVideoId;
	}

	@JSON
	public long getViolationId() {
		return _violationId;
	}

	public void setViolationId(long violationId) {
		_columnBitmask |= VIOLATIONID_COLUMN_BITMASK;

		if (!_setOriginalViolationId) {
			_setOriginalViolationId = true;

			_originalViolationId = _violationId;
		}

		_violationId = violationId;
	}

	public long getOriginalViolationId() {
		return _originalViolationId;
	}

	@JSON
	public long getVideoId() {
		return _videoId;
	}

	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public Date getDate_() {
		return _date_;
	}

	public void setDate_(Date date_) {
		_columnBitmask = -1L;

		_date_ = date_;
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ViolationVideoEntry toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ViolationVideoEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					ViolationVideoEntry.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ViolationVideoEntryImpl violationVideoEntryImpl = new ViolationVideoEntryImpl();

		violationVideoEntryImpl.setViolationVideoId(getViolationVideoId());
		violationVideoEntryImpl.setViolationId(getViolationId());
		violationVideoEntryImpl.setVideoId(getVideoId());
		violationVideoEntryImpl.setUserId(getUserId());
		violationVideoEntryImpl.setDate_(getDate_());
		violationVideoEntryImpl.setDescription(getDescription());

		violationVideoEntryImpl.resetOriginalValues();

		return violationVideoEntryImpl;
	}

	public int compareTo(ViolationVideoEntry violationVideoEntry) {
		int value = 0;

		value = DateUtil.compareTo(getDate_(), violationVideoEntry.getDate_());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ViolationVideoEntry violationVideoEntry = null;

		try {
			violationVideoEntry = (ViolationVideoEntry)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = violationVideoEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ViolationVideoEntryModelImpl violationVideoEntryModelImpl = this;

		violationVideoEntryModelImpl._originalViolationId = violationVideoEntryModelImpl._violationId;

		violationVideoEntryModelImpl._setOriginalViolationId = false;

		violationVideoEntryModelImpl._originalVideoId = violationVideoEntryModelImpl._videoId;

		violationVideoEntryModelImpl._setOriginalVideoId = false;

		violationVideoEntryModelImpl._originalUserId = violationVideoEntryModelImpl._userId;

		violationVideoEntryModelImpl._setOriginalUserId = false;

		violationVideoEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ViolationVideoEntry> toCacheModel() {
		ViolationVideoEntryCacheModel violationVideoEntryCacheModel = new ViolationVideoEntryCacheModel();

		violationVideoEntryCacheModel.violationVideoId = getViolationVideoId();

		violationVideoEntryCacheModel.violationId = getViolationId();

		violationVideoEntryCacheModel.videoId = getVideoId();

		violationVideoEntryCacheModel.userId = getUserId();

		Date date_ = getDate_();

		if (date_ != null) {
			violationVideoEntryCacheModel.date_ = date_.getTime();
		}
		else {
			violationVideoEntryCacheModel.date_ = Long.MIN_VALUE;
		}

		violationVideoEntryCacheModel.description = getDescription();

		String description = violationVideoEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			violationVideoEntryCacheModel.description = null;
		}

		return violationVideoEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{violationVideoId=");
		sb.append(getViolationVideoId());
		sb.append(", violationId=");
		sb.append(getViolationId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", date_=");
		sb.append(getDate_());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("vn.com.fis.portal.model.ViolationVideoEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>violationVideoId</column-name><column-value><![CDATA[");
		sb.append(getViolationVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>violationId</column-name><column-value><![CDATA[");
		sb.append(getViolationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date_</column-name><column-value><![CDATA[");
		sb.append(getDate_());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ViolationVideoEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ViolationVideoEntry.class
		};
	private long _violationVideoId;
	private long _violationId;
	private long _originalViolationId;
	private boolean _setOriginalViolationId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _date_;
	private String _description;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private ViolationVideoEntry _escapedModelProxy;
}