/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.fis.portal.model.VideoGroupEntry;
import vn.com.fis.portal.model.VideoGroupEntryModel;
import vn.com.fis.portal.model.VideoGroupEntrySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VideoGroupEntry service. Represents a row in the &quot;TBL_VIDEO_GROUP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.fis.portal.model.VideoGroupEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoGroupEntryImpl}.
 * </p>
 *
 * @author loind
 * @see VideoGroupEntryImpl
 * @see vn.com.fis.portal.model.VideoGroupEntry
 * @see vn.com.fis.portal.model.VideoGroupEntryModel
 * @generated
 */
@JSON(strict = true)
public class VideoGroupEntryModelImpl extends BaseModelImpl<VideoGroupEntry>
	implements VideoGroupEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video group entry model instance should use the {@link vn.com.fis.portal.model.VideoGroupEntry} interface instead.
	 */
	public static final String TABLE_NAME = "TBL_VIDEO_GROUP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "videoGroupId", Types.BIGINT },
			{ "videoGroupName", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TBL_VIDEO_GROUP (videoGroupId LONG not null primary key,videoGroupName VARCHAR(75) null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TBL_VIDEO_GROUP";
	public static final String ORDER_BY_JPQL = " ORDER BY videoGroupEntry.videoGroupName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TBL_VIDEO_GROUP.videoGroupName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.com.fis.portal.model.VideoGroupEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.com.fis.portal.model.VideoGroupEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.com.fis.portal.model.VideoGroupEntry"),
			true);
	public static long VIDEOGROUPNAME_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VideoGroupEntry toModel(VideoGroupEntrySoap soapModel) {
		VideoGroupEntry model = new VideoGroupEntryImpl();

		model.setVideoGroupId(soapModel.getVideoGroupId());
		model.setVideoGroupName(soapModel.getVideoGroupName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VideoGroupEntry> toModels(
		VideoGroupEntrySoap[] soapModels) {
		List<VideoGroupEntry> models = new ArrayList<VideoGroupEntry>(soapModels.length);

		for (VideoGroupEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.com.fis.portal.model.VideoGroupEntry"));

	public VideoGroupEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _videoGroupId;
	}

	public void setPrimaryKey(long primaryKey) {
		setVideoGroupId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_videoGroupId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return VideoGroupEntry.class;
	}

	public String getModelClassName() {
		return VideoGroupEntry.class.getName();
	}

	@JSON
	public long getVideoGroupId() {
		return _videoGroupId;
	}

	public void setVideoGroupId(long videoGroupId) {
		_videoGroupId = videoGroupId;
	}

	@JSON
	public String getVideoGroupName() {
		if (_videoGroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _videoGroupName;
		}
	}

	public void setVideoGroupName(String videoGroupName) {
		_columnBitmask = -1L;

		if (_originalVideoGroupName == null) {
			_originalVideoGroupName = _videoGroupName;
		}

		_videoGroupName = videoGroupName;
	}

	public String getOriginalVideoGroupName() {
		return GetterUtil.getString(_originalVideoGroupName);
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VideoGroupEntry toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (VideoGroupEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					VideoGroupEntry.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		VideoGroupEntryImpl videoGroupEntryImpl = new VideoGroupEntryImpl();

		videoGroupEntryImpl.setVideoGroupId(getVideoGroupId());
		videoGroupEntryImpl.setVideoGroupName(getVideoGroupName());
		videoGroupEntryImpl.setDescription(getDescription());

		videoGroupEntryImpl.resetOriginalValues();

		return videoGroupEntryImpl;
	}

	public int compareTo(VideoGroupEntry videoGroupEntry) {
		int value = 0;

		value = getVideoGroupName()
					.compareTo(videoGroupEntry.getVideoGroupName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VideoGroupEntry videoGroupEntry = null;

		try {
			videoGroupEntry = (VideoGroupEntry)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = videoGroupEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VideoGroupEntryModelImpl videoGroupEntryModelImpl = this;

		videoGroupEntryModelImpl._originalVideoGroupName = videoGroupEntryModelImpl._videoGroupName;

		videoGroupEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VideoGroupEntry> toCacheModel() {
		VideoGroupEntryCacheModel videoGroupEntryCacheModel = new VideoGroupEntryCacheModel();

		videoGroupEntryCacheModel.videoGroupId = getVideoGroupId();

		videoGroupEntryCacheModel.videoGroupName = getVideoGroupName();

		String videoGroupName = videoGroupEntryCacheModel.videoGroupName;

		if ((videoGroupName != null) && (videoGroupName.length() == 0)) {
			videoGroupEntryCacheModel.videoGroupName = null;
		}

		videoGroupEntryCacheModel.description = getDescription();

		String description = videoGroupEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			videoGroupEntryCacheModel.description = null;
		}

		return videoGroupEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{videoGroupId=");
		sb.append(getVideoGroupId());
		sb.append(", videoGroupName=");
		sb.append(getVideoGroupName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("vn.com.fis.portal.model.VideoGroupEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>videoGroupId</column-name><column-value><![CDATA[");
		sb.append(getVideoGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoGroupName</column-name><column-value><![CDATA[");
		sb.append(getVideoGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VideoGroupEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			VideoGroupEntry.class
		};
	private long _videoGroupId;
	private String _videoGroupName;
	private String _originalVideoGroupName;
	private String _description;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private VideoGroupEntry _escapedModelProxy;
}