/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CategoryVideoEntry service. Represents a row in the &quot;TBL_CATEGORY_VIDEO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.CategoryVideoEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.CategoryVideoEntryImpl}.
 * </p>
 *
 * @author loind
 * @see CategoryVideoEntry
 * @see vn.com.fis.portal.model.impl.CategoryVideoEntryImpl
 * @see vn.com.fis.portal.model.impl.CategoryVideoEntryModelImpl
 * @generated
 */
public interface CategoryVideoEntryModel extends BaseModel<CategoryVideoEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a category video entry model instance should use the {@link CategoryVideoEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this category video entry.
	 *
	 * @return the primary key of this category video entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this category video entry.
	 *
	 * @param primaryKey the primary key of this category video entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category viceo ID of this category video entry.
	 *
	 * @return the category viceo ID of this category video entry
	 */
	public long getCategoryViceoId();

	/**
	 * Sets the category viceo ID of this category video entry.
	 *
	 * @param categoryViceoId the category viceo ID of this category video entry
	 */
	public void setCategoryViceoId(long categoryViceoId);

	/**
	 * Returns the category ID of this category video entry.
	 *
	 * @return the category ID of this category video entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this category video entry.
	 *
	 * @param categoryId the category ID of this category video entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the video ID of this category video entry.
	 *
	 * @return the video ID of this category video entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this category video entry.
	 *
	 * @param videoId the video ID of this category video entry
	 */
	public void setVideoId(long videoId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CategoryVideoEntry categoryVideoEntry);

	public int hashCode();

	public CacheModel<CategoryVideoEntry> toCacheModel();

	public CategoryVideoEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}