/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ContactGroupContactEntry service. Represents a row in the &quot;TBL_CONTACT_GROUP_CONTACT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.ContactGroupContactEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.ContactGroupContactEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ContactGroupContactEntry
 * @see vn.com.fis.portal.model.impl.ContactGroupContactEntryImpl
 * @see vn.com.fis.portal.model.impl.ContactGroupContactEntryModelImpl
 * @generated
 */
public interface ContactGroupContactEntryModel extends BaseModel<ContactGroupContactEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact group contact entry model instance should use the {@link ContactGroupContactEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this contact group contact entry.
	 *
	 * @return the primary key of this contact group contact entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact group contact entry.
	 *
	 * @param primaryKey the primary key of this contact group contact entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact group contact ID of this contact group contact entry.
	 *
	 * @return the contact group contact ID of this contact group contact entry
	 */
	public long getContactGroupContactId();

	/**
	 * Sets the contact group contact ID of this contact group contact entry.
	 *
	 * @param contactGroupContactId the contact group contact ID of this contact group contact entry
	 */
	public void setContactGroupContactId(long contactGroupContactId);

	/**
	 * Returns the contact ID of this contact group contact entry.
	 *
	 * @return the contact ID of this contact group contact entry
	 */
	@AutoEscape
	public String getContactId();

	/**
	 * Sets the contact ID of this contact group contact entry.
	 *
	 * @param contactId the contact ID of this contact group contact entry
	 */
	public void setContactId(String contactId);

	/**
	 * Returns the contact group ID of this contact group contact entry.
	 *
	 * @return the contact group ID of this contact group contact entry
	 */
	@AutoEscape
	public String getContactGroupId();

	/**
	 * Sets the contact group ID of this contact group contact entry.
	 *
	 * @param contactGroupId the contact group ID of this contact group contact entry
	 */
	public void setContactGroupId(String contactGroupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ContactGroupContactEntry contactGroupContactEntry);

	public int hashCode();

	public CacheModel<ContactGroupContactEntry> toCacheModel();

	public ContactGroupContactEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}