/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoUserTransactionEntry service. Represents a row in the &quot;TBL_VIDEO_USER_TRANSACTION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.VideoUserTransactionEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.VideoUserTransactionEntryImpl}.
 * </p>
 *
 * @author loind
 * @see VideoUserTransactionEntry
 * @see vn.com.fis.portal.model.impl.VideoUserTransactionEntryImpl
 * @see vn.com.fis.portal.model.impl.VideoUserTransactionEntryModelImpl
 * @generated
 */
public interface VideoUserTransactionEntryModel extends BaseModel<VideoUserTransactionEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video user transaction entry model instance should use the {@link VideoUserTransactionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this video user transaction entry.
	 *
	 * @return the primary key of this video user transaction entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video user transaction entry.
	 *
	 * @param primaryKey the primary key of this video user transaction entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the transaction ID of this video user transaction entry.
	 *
	 * @return the transaction ID of this video user transaction entry
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this video user transaction entry.
	 *
	 * @param transactionId the transaction ID of this video user transaction entry
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the transaction code of this video user transaction entry.
	 *
	 * @return the transaction code of this video user transaction entry
	 */
	public long getTransactionCode();

	/**
	 * Sets the transaction code of this video user transaction entry.
	 *
	 * @param transactionCode the transaction code of this video user transaction entry
	 */
	public void setTransactionCode(long transactionCode);

	/**
	 * Returns the date_ of this video user transaction entry.
	 *
	 * @return the date_ of this video user transaction entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this video user transaction entry.
	 *
	 * @param date_ the date_ of this video user transaction entry
	 */
	public void setDate_(Date date_);

	/**
	 * Returns the video ID of this video user transaction entry.
	 *
	 * @return the video ID of this video user transaction entry
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video user transaction entry.
	 *
	 * @param videoId the video ID of this video user transaction entry
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the user ID of this video user transaction entry.
	 *
	 * @return the user ID of this video user transaction entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this video user transaction entry.
	 *
	 * @param userId the user ID of this video user transaction entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this video user transaction entry.
	 *
	 * @return the user uuid of this video user transaction entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this video user transaction entry.
	 *
	 * @param userUuid the user uuid of this video user transaction entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the receiver ID of this video user transaction entry.
	 *
	 * @return the receiver ID of this video user transaction entry
	 */
	public long getReceiverId();

	/**
	 * Sets the receiver ID of this video user transaction entry.
	 *
	 * @param receiverId the receiver ID of this video user transaction entry
	 */
	public void setReceiverId(long receiverId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VideoUserTransactionEntry videoUserTransactionEntry);

	public int hashCode();

	public CacheModel<VideoUserTransactionEntry> toCacheModel();

	public VideoUserTransactionEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}