/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CategoryEntry service. Represents a row in the &quot;TBL_CATEGORY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.CategoryEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.CategoryEntryImpl}.
 * </p>
 *
 * @author loind
 * @see CategoryEntry
 * @see vn.com.fis.portal.model.impl.CategoryEntryImpl
 * @see vn.com.fis.portal.model.impl.CategoryEntryModelImpl
 * @generated
 */
public interface CategoryEntryModel extends BaseModel<CategoryEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a category entry model instance should use the {@link CategoryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this category entry.
	 *
	 * @return the primary key of this category entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this category entry.
	 *
	 * @param primaryKey the primary key of this category entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this category entry.
	 *
	 * @return the category ID of this category entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this category entry.
	 *
	 * @param categoryId the category ID of this category entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the category name of this category entry.
	 *
	 * @return the category name of this category entry
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this category entry.
	 *
	 * @param categoryName the category name of this category entry
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the description of this category entry.
	 *
	 * @return the description of this category entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this category entry.
	 *
	 * @param description the description of this category entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this category entry.
	 *
	 * @return the status of this category entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this category entry.
	 *
	 * @param status the status of this category entry
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CategoryEntry categoryEntry);

	public int hashCode();

	public CacheModel<CategoryEntry> toCacheModel();

	public CategoryEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}