/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FolderEntry service. Represents a row in the &quot;TBL_FOLDER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.FolderEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.FolderEntryImpl}.
 * </p>
 *
 * @author loind
 * @see FolderEntry
 * @see vn.com.fis.portal.model.impl.FolderEntryImpl
 * @see vn.com.fis.portal.model.impl.FolderEntryModelImpl
 * @generated
 */
public interface FolderEntryModel extends BaseModel<FolderEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a folder entry model instance should use the {@link FolderEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this folder entry.
	 *
	 * @return the primary key of this folder entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this folder entry.
	 *
	 * @param primaryKey the primary key of this folder entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the folder ID of this folder entry.
	 *
	 * @return the folder ID of this folder entry
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this folder entry.
	 *
	 * @param folderId the folder ID of this folder entry
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the folder name of this folder entry.
	 *
	 * @return the folder name of this folder entry
	 */
	@AutoEscape
	public String getFolderName();

	/**
	 * Sets the folder name of this folder entry.
	 *
	 * @param folderName the folder name of this folder entry
	 */
	public void setFolderName(String folderName);

	/**
	 * Returns the description of this folder entry.
	 *
	 * @return the description of this folder entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this folder entry.
	 *
	 * @param description the description of this folder entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the create date of this folder entry.
	 *
	 * @return the create date of this folder entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this folder entry.
	 *
	 * @param createDate the create date of this folder entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this folder entry.
	 *
	 * @return the modified date of this folder entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this folder entry.
	 *
	 * @param modifiedDate the modified date of this folder entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the folder ID parent of this folder entry.
	 *
	 * @return the folder ID parent of this folder entry
	 */
	public long getFolderIdParent();

	/**
	 * Sets the folder ID parent of this folder entry.
	 *
	 * @param folderIdParent the folder ID parent of this folder entry
	 */
	public void setFolderIdParent(long folderIdParent);

	/**
	 * Returns the user ID of this folder entry.
	 *
	 * @return the user ID of this folder entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this folder entry.
	 *
	 * @param userId the user ID of this folder entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this folder entry.
	 *
	 * @return the user uuid of this folder entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this folder entry.
	 *
	 * @param userUuid the user uuid of this folder entry
	 */
	public void setUserUuid(String userUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FolderEntry folderEntry);

	public int hashCode();

	public CacheModel<FolderEntry> toCacheModel();

	public FolderEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}