/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceTransactionEntry service. Represents a row in the &quot;TBL_SERVICE_TRANSACTION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.ServiceTransactionEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.ServiceTransactionEntryImpl}.
 * </p>
 *
 * @author loind
 * @see ServiceTransactionEntry
 * @see vn.com.fis.portal.model.impl.ServiceTransactionEntryImpl
 * @see vn.com.fis.portal.model.impl.ServiceTransactionEntryModelImpl
 * @generated
 */
public interface ServiceTransactionEntryModel extends BaseModel<ServiceTransactionEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service transaction entry model instance should use the {@link ServiceTransactionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this service transaction entry.
	 *
	 * @return the primary key of this service transaction entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service transaction entry.
	 *
	 * @param primaryKey the primary key of this service transaction entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the transaction ID of this service transaction entry.
	 *
	 * @return the transaction ID of this service transaction entry
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this service transaction entry.
	 *
	 * @param transactionId the transaction ID of this service transaction entry
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the transaction code of this service transaction entry.
	 *
	 * @return the transaction code of this service transaction entry
	 */
	public int getTransactionCode();

	/**
	 * Sets the transaction code of this service transaction entry.
	 *
	 * @param transactionCode the transaction code of this service transaction entry
	 */
	public void setTransactionCode(int transactionCode);

	/**
	 * Returns the date_ of this service transaction entry.
	 *
	 * @return the date_ of this service transaction entry
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this service transaction entry.
	 *
	 * @param date_ the date_ of this service transaction entry
	 */
	public void setDate_(Date date_);

	/**
	 * Returns the user ID of this service transaction entry.
	 *
	 * @return the user ID of this service transaction entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service transaction entry.
	 *
	 * @param userId the user ID of this service transaction entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service transaction entry.
	 *
	 * @return the user uuid of this service transaction entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service transaction entry.
	 *
	 * @param userUuid the user uuid of this service transaction entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the service ID of this service transaction entry.
	 *
	 * @return the service ID of this service transaction entry
	 */
	public long getServiceId();

	/**
	 * Sets the service ID of this service transaction entry.
	 *
	 * @param serviceId the service ID of this service transaction entry
	 */
	public void setServiceId(long serviceId);

	/**
	 * Returns the service status of this service transaction entry.
	 *
	 * @return the service status of this service transaction entry
	 */
	public int getServiceStatus();

	/**
	 * Sets the service status of this service transaction entry.
	 *
	 * @param serviceStatus the service status of this service transaction entry
	 */
	public void setServiceStatus(int serviceStatus);

	/**
	 * Returns the service start date of this service transaction entry.
	 *
	 * @return the service start date of this service transaction entry
	 */
	public Date getServiceStartDate();

	/**
	 * Sets the service start date of this service transaction entry.
	 *
	 * @param serviceStartDate the service start date of this service transaction entry
	 */
	public void setServiceStartDate(Date serviceStartDate);

	/**
	 * Returns the service stop date of this service transaction entry.
	 *
	 * @return the service stop date of this service transaction entry
	 */
	public Date getServiceStopDate();

	/**
	 * Sets the service stop date of this service transaction entry.
	 *
	 * @param serviceStopDate the service stop date of this service transaction entry
	 */
	public void setServiceStopDate(Date serviceStopDate);

	/**
	 * Returns the service end date of this service transaction entry.
	 *
	 * @return the service end date of this service transaction entry
	 */
	public Date getServiceEndDate();

	/**
	 * Sets the service end date of this service transaction entry.
	 *
	 * @param serviceEndDate the service end date of this service transaction entry
	 */
	public void setServiceEndDate(Date serviceEndDate);

	/**
	 * Returns the service package ID of this service transaction entry.
	 *
	 * @return the service package ID of this service transaction entry
	 */
	public long getServicePackageId();

	/**
	 * Sets the service package ID of this service transaction entry.
	 *
	 * @param servicePackageId the service package ID of this service transaction entry
	 */
	public void setServicePackageId(long servicePackageId);

	/**
	 * Returns the package date of this service transaction entry.
	 *
	 * @return the package date of this service transaction entry
	 */
	public Date getPackageDate();

	/**
	 * Sets the package date of this service transaction entry.
	 *
	 * @param packageDate the package date of this service transaction entry
	 */
	public void setPackageDate(Date packageDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ServiceTransactionEntry serviceTransactionEntry);

	public int hashCode();

	public CacheModel<ServiceTransactionEntry> toCacheModel();

	public ServiceTransactionEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}