/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.com.fis.portal.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserServiceEntry service. Represents a row in the &quot;TBL_USER_SERVICE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.fis.portal.model.impl.UserServiceEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.fis.portal.model.impl.UserServiceEntryImpl}.
 * </p>
 *
 * @author loind
 * @see UserServiceEntry
 * @see vn.com.fis.portal.model.impl.UserServiceEntryImpl
 * @see vn.com.fis.portal.model.impl.UserServiceEntryModelImpl
 * @generated
 */
public interface UserServiceEntryModel extends BaseModel<UserServiceEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user service entry model instance should use the {@link UserServiceEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this user service entry.
	 *
	 * @return the primary key of this user service entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user service entry.
	 *
	 * @param primaryKey the primary key of this user service entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user service ID of this user service entry.
	 *
	 * @return the user service ID of this user service entry
	 */
	public long getUserServiceId();

	/**
	 * Sets the user service ID of this user service entry.
	 *
	 * @param userServiceId the user service ID of this user service entry
	 */
	public void setUserServiceId(long userServiceId);

	/**
	 * Returns the user ID of this user service entry.
	 *
	 * @return the user ID of this user service entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user service entry.
	 *
	 * @param userId the user ID of this user service entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user service entry.
	 *
	 * @return the user uuid of this user service entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user service entry.
	 *
	 * @param userUuid the user uuid of this user service entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the service ID of this user service entry.
	 *
	 * @return the service ID of this user service entry
	 */
	public long getServiceId();

	/**
	 * Sets the service ID of this user service entry.
	 *
	 * @param serviceId the service ID of this user service entry
	 */
	public void setServiceId(long serviceId);

	/**
	 * Returns the service status of this user service entry.
	 *
	 * @return the service status of this user service entry
	 */
	public int getServiceStatus();

	/**
	 * Sets the service status of this user service entry.
	 *
	 * @param serviceStatus the service status of this user service entry
	 */
	public void setServiceStatus(int serviceStatus);

	/**
	 * Returns the service start date of this user service entry.
	 *
	 * @return the service start date of this user service entry
	 */
	public Date getServiceStartDate();

	/**
	 * Sets the service start date of this user service entry.
	 *
	 * @param serviceStartDate the service start date of this user service entry
	 */
	public void setServiceStartDate(Date serviceStartDate);

	/**
	 * Returns the service stop date of this user service entry.
	 *
	 * @return the service stop date of this user service entry
	 */
	public Date getServiceStopDate();

	/**
	 * Sets the service stop date of this user service entry.
	 *
	 * @param serviceStopDate the service stop date of this user service entry
	 */
	public void setServiceStopDate(Date serviceStopDate);

	/**
	 * Returns the service package ID of this user service entry.
	 *
	 * @return the service package ID of this user service entry
	 */
	public long getServicePackageId();

	/**
	 * Sets the service package ID of this user service entry.
	 *
	 * @param servicePackageId the service package ID of this user service entry
	 */
	public void setServicePackageId(long servicePackageId);

	/**
	 * Returns the package date of this user service entry.
	 *
	 * @return the package date of this user service entry
	 */
	public Date getPackageDate();

	/**
	 * Sets the package date of this user service entry.
	 *
	 * @param packageDate the package date of this user service entry
	 */
	public void setPackageDate(Date packageDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserServiceEntry userServiceEntry);

	public int hashCode();

	public CacheModel<UserServiceEntry> toCacheModel();

	public UserServiceEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}